# Generated by Django 6.0.3 on 2026-04-09 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='total_price',
        ),
    ]
